### ISSUE TITLE
cyclonedx-python-lib doesn't work with the latest versions of setuptools

### ISSUE THREAD

**Issue by jocassid** [CycloneDX/cyclonedx-python-lib#100]
I received the following error while attempting to upgrade to the latest version of setuptools:  cyclonedx-python-lib 0.11.1 requires setuptools<51.0.0,>=50.3.2, but you have setuptools 59.6.0 which is incompatible.

Running `pip install setuptools==50.3.2` was my work-around for this problem

**Comment by madpah** [comment]
@jocassid - please upgrade to a version of `cyclonedx-python-lib` `>=0.13.0` as we have notably loosened the dependency requirements. This will allow `setuptools` `>=47.0.0`.
