### ISSUE TITLE
Documentation is failing to build and publish since #93 was merged

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#106]
See https://github.com/CycloneDX/cyclonedx-python-lib/runs/4595932920?check_suite_focus=true.

This appears to be the case since #93 was merged.

FYI: @jkowalleck

**Comment by jkowalleck** [comment]
python markdown requires `importlib_metadata` which is not installed. hm, that  is strange.
will look into it.

**Comment by madpah** [comment]
I can't get it to fail locally @jkowalleck ? Very weird.

**Comment by madpah** [comment]
Last successful run (https://github.com/CycloneDX/cyclonedx-python-lib/runs/4584812203?check_suite_focus=true) pulled in a **newer** version of `Installing markdown (3.3.6)` than the latest attempt: `Installing markdown (3.3.5)`

**Comment by madpah** [comment]
I'll regen `poetry.lock` @jkowalleck

**Comment by madpah** [comment]
And when doing so I get this:
```
<debug>PackageInfo:</debug> Invalid constraint (importlib-metadata (>='4.4') ; python_version < "3.10") found in markdown-3.3.5 dependencies, skipping
```

**Comment by madpah** [comment]
So - looks like the root cause is related to bumping `flake8` `>=4.0.1':

If we directly had `markdown==3.3.6` as a dev-dependency:
```
poetry update                                                                                      
Updating dependencies
Resolving dependencies... (0.1s)

  SolverProblemError

  Because no versions of markdown match >3.3.6,<4.0.0
   and markdown (3.3.6) depends on importlib-metadata (>=4.4), markdown (>=3.3.6,<4.0.0) requires importlib-metadata (>=4.4).
  And because flake8 (4.0.1) depends on importlib-metadata (<4.3)
   and no versions of flake8 match >4.0.1,<5.0.0, markdown (>=3.3.6,<4.0.0) is incompatible with flake8 (>=4.0.1,<5.0.0).
  So, because cyclonedx-python-lib depends on both flake8 (^4.0.1) and markdown (^3.3.6), version solving failed.
```

**Comment by madpah** [comment]
Isolating dependencies for documentation generation has resolved this immediate problem.
