### ISSUE TITLE
[BUG] Serializers should omit `ExternalReferenceType.RELEASE_NOTES` when Schema Version < 1.4

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#133]
:100:  note for mysel: see of 1.3 serializers ommit this

_Originally posted by @jkowalleck in https://github.com/CycloneDX/cyclonedx-python-lib/pull/108#discussion_r780199219_

**Comment by jkowalleck** [comment]
when i wrote my note, i dd not actually check, if omitting `ExternalReferenceType.RELEASE_NOTES` was doe already.
it was more a todo for myself. 

did the research now: 
- JSON omits releaseNotes if unsupported - via https://github.com/CycloneDX/cyclonedx-python-lib/blob/dec63de950e0ad81cbb51373b0e647bce551297e/cyclonedx/output/json.py#L92-L93
- XML omits releaseNotes if unsupported - via https://github.com/CycloneDX/cyclonedx-python-lib/blob/dec63de950e0ad81cbb51373b0e647bce551297e/cyclonedx/output/xml.py#L201-L202

**Comment by jkowalleck** [comment]
reasearch done, all good. i will clone the Issue, then.

FYI @madpah
