### ISSUE TITLE
[FEATURE] Ensure `bom-ref` for `Component` and `Vulnerability` have a (unique) value

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#141]
Currently our models rely on the consumer to specifiy/provide a value for a Component or Vulnerability's `bom-ref`.

In previous versions of this library, the `purl` was automatically used for this purpose (for Component) but this was removed as a Component may not have a `purl`.

As pointed out in https://github.com/sonatype-nexus-community/jake/issues/91, for Vulnerabilities to be able to specify which Components are affected (in 1.4), Components must have a `bom-ref` - see [here](https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_affects_items_versions).

It's worth noting that `bom-ref` is optional within the schema for both Component and Vulnerability.

This Feature will look to assign a UUID as the `bom-ref` if a value has not been provided by the consumer.

**Comment by jkowalleck** [comment]
some related thoughts: https://github.com/CycloneDX/cyclonedx-php-library/blob/master/docs/dev/decisions/BomDependencyDataModel.md

**Comment by damiencarol** [comment]
@madpah can't we use PURL string as the bom-ref for component? the specification do that in the example.
Could be better than generate a UUID and keep a trace of it, etc...

**Comment by madpah** [comment]
> @madpah can't we use PURL string as the bom-ref for component? the specification do that in the examples. Could be better than generate a UUID and keep a trace of it, etc... see https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.4/valid-vulnerability-1.4.json

@damiencarol - we can't use a PURL in most circumstances, but the model provided for by this library allows that to be the case. This PR was a precursor to a full fix in `jake` btw.

**Comment by damiencarol** [comment]
will test it as soon as it's ready.
FYI: I'm working on makingJake importing works for https://github.com/DefectDojo/django-DefectDojo
