### ISSUE TITLE
`__hash__` implementation in `Component` attempts to hash unhashable properties list if present

### ISSUE THREAD

**Issue by 0t1s1** [CycloneDX/cyclonedx-python-lib#153]
The `Component` class' `__hash__` implementation [attempts to hash](https://github.com/CycloneDX/cyclonedx-python-lib/blob/41781819e2de8f650271e7de11d395fa43939f22/cyclonedx/model/component.py#L514) an unhashable list of `Property` objects if present. This prevents `Component` objects from being compared, which in turn prevents one from adding `Component` objects to `Bom` objects via `Bom`'s `add_component` method.

Example:
```
from cyclonedx.model.component import Component
from cyclonedx.model import Property
component1 = Component("component 1", properties=[Property("prop 1", "value 1")])
component2 = Component("component 2")
component1 == component2
```
Results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.8/site-packages/cyclonedx/model/component.py", line 508, in __eq__
    return hash(other) == hash(self)
  File "/lib/python3.8/site-packages/cyclonedx/model/component.py", line 512, in __hash__
    return hash((
TypeError: unhashable type: 'list'
```

Library version: 1.3.0
OS: CentOS 8

**Comment by jkowalleck** [comment]
expected fix: 
1. implement unit tests  that test the `hash()` on objects that are expected to hash. 
2. implement the `__hash__()` method in the classes that need one.

**Comment by madpah** [comment]
Agree @jkowalleck. This will require a fair bit of work to do "right", but will include a temp fix for this in the next release and leave this open to track a proper fix.

**Comment by madpah** [comment]
Thanks for the report @0t1s1 !
