### ISSUE TITLE
[BREAKING] no default schema

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#171]
caused by #163 / #164

proposal / expected outcome
* do not  use a default schema at all
* rename `DEFAULT_SCHEMA_VERSION` to `LATEST_SUPPORTED_SCHEMA_VERSION`
* there is no defaulting or magic when it comes to SchemaVersions. Users have to input a valid value..

motivation: 
* no more breaking changes, when a new schema version is added. they are just features the users can plug.

**Comment by madpah** [comment]
https://pypi.org/project/cyclonedx-python-lib/2.0.0/ released
