### ISSUE TITLE
Typo in `License()` parameter `spxd_license_id`  - should be `spdx_license_id`

### ISSUE THREAD

**Issue by schlenk** [CycloneDX/cyclonedx-python-lib#176]
class License(builtins.object)
 |  License(spxd_license_id: Optional[str] = None

The parameter is prefixed by 'spxd' but the license page referenced is called "SPDX" (https://spdx.dev/)

Might be API breaking to change it.

Found in cyclonedx-python-lib 1.3.0

**Comment by jkowalleck** [comment]
Could you elaborate, @schlenk ? 

What seams to be the issue? What is an acceptable solution? how would you suggest to solve the situation?

**An addition** you could open a pull request to show a possible mitigation. 
If you do so, 
1. please read https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CONTRIBUTING.md
2. be aware that a breaking change is already in the making - so no problem if you intend to introduce breaking changes.
  * see https://github.com/CycloneDX/cyclonedx-python-lib/pull/148
  * you could branch out from `feat/add-bom-services`  
      and pull request into that branch.

**Comment by schlenk** [comment]
The referenced standard is called "SPDX", so the license_id referenced in the id property and set by the constructor is a "spdx_license_id". But the constructor named parameter is called "spxd_license_id".

Calling the parameter "spxd_license_id" is confusing due to the typo (xd instead of dx) in the identifier.

If the API is broken with 2.0.0 anyway, i would simply rename the parameter to the better fitting one.

**Comment by jkowalleck** [comment]
@madpah  as we are planning to have most parameters forced to be keys, this typo should be addressed.
in fact, i see it was fixed already, in https://github.com/CycloneDX/cyclonedx-python-lib/blob/0d82c019afce3e4aefe56bff9607cfd60186c6b0/cyclonedx/model/__init__.py#L481
via #160

therefore i marked the relevant PRs to close this very PR, after the fact.
