### ISSUE TITLE
`License` does not serialize `license_url` to the output.

### ISSUE THREAD

**Issue by schlenk** [CycloneDX/cyclonedx-python-lib#179]
The `license_url` optional field is not serialized to the XML output.
The spec recommends to also add the ExternalReference with type LICENSE, but i would expect the URL in the output, if it is given as part of the License type.

Probably just missing in the code here:

https://github.com/CycloneDX/cyclonedx-python-lib/blob/9e802582bd9b9bdd0e1e91a0af551d3f2190fb5e/cyclonedx/output/xml.py#L159

Seen using cyclonedx-python-lib 1.3.0, but the code seems identical in the main branch.

**Comment by madpah** [comment]
Hi @schlenk - thanks for the report. Totally correct here - bug discovered.

Will get this fixed and into the next release (due this week).

**Comment by madpah** [comment]
https://pypi.org/project/cyclonedx-python-lib/2.0.0/ released.
