### ISSUE TITLE
[DEV] Add pre-commit hooks

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#190]
Various improvement features had added tooling (which is called out in [CONTRIBUTING.md](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CONTRIBUTING.md)) but life could be easier for developers by adding these as [pre-commit](https://pre-commit.com/) hooks.

See:
- #85
- #86

**Comment by jkowalleck** [comment]
another pre-commit hook, besides isort, could be: 
* auto-pep8
* and as a gate-keeper: flake8, mypy etc .... but we have them running in tox - so a tox-call would be the solution, then.
