### ISSUE TITLE
[FEATURE] `Bom` should enforce unique constraints

### ISSUE THREAD

**Issue by RodneyRichardson** [CycloneDX/cyclonedx-python-lib#239]
The Bom class stores components, services and external_references in a `set` (or `SortedSet`: #235). This does not enforce, for example, that the bom_ref of each component should be unique.

It should probably store these in a SortedDict instead, keyed on bom_ref.

**Comment by jkowalleck** [comment]
there is no need for a unique bom-ref value in a set.
the constraint is only relevant when it comes to normalization/serialization.

Therefore a BomRefDiscriminator can be used. 
Example implementations: 
* https://github.com/CycloneDX/cyclonedx-javascript-library/blob/1.0-dev/src/serialize/bomRefDiscriminator.ts
* https://github.com/CycloneDX/cyclonedx-php-library/blob/master/src/Core/Serialize/BomRefDiscriminator.php

**Comment by jkowalleck** [comment]
will work on this soon
