### ISSUE TITLE
QUESTION: How to represent a Component (dependency) with multiple download formats?

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#26]
It's commonplace in the Python ecosystem for a given package version to be available in both `whl` and `tar.gz` formats (and possibly others.

When we define a `Component` in a CycloneDX schema, this `Component` can include a list of hashes that provide an integrity to the definition. This is complicated in the Python eco-system as we do not know? which format/download has been used.

For example, in a `Pipfile.lock` for `toml==0.10.2` you will see two hashes which correlate to both the `whl` and `tar.gz` formats:
```
"hashes": [
    "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b",
    "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"
],
```

Including both hashes may be the correct answer, but I'm seeking clarification from the @CycloneDX/core-team prior to implementation.

**Comment by stevespringett** [comment]
Include the hash for the component that represents reality. 

If there are multiple distributions of a component, then I'd recommend using the `distribution` external reference type. Refer to https://cyclonedx.org/use-cases/#external-references. Each `distribution` can have its own set of hashes.
