### ISSUE TITLE
[CI] Replace `python-semantic-release` / re-engineer release pipelines

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#285]
We currently use and rely upon `python-semantic-release` to detect the next version and publish to PyPI and GitHub.

Over the past couple of months, this project has proved unstable and has broken numerous publishing pipelines and thus we are considering replacing this to ensure stability for this project.

FYI @jkowalleck

**Comment by jkowalleck** [comment]
closed.
found a working version / solution
