### ISSUE TITLE
[CHORE] revert the v3.0.0 that was triggered by error

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#286]
`python-semantic-release`  has/had an error (besides ##285),
that triggered a release v3.0.0 when it should have triggered v2.7.1 ... 

v2.7.1 was triggered manually

the remains of v3.0.0 need to be removed, 
as an actual v3 will be released eventually.

- [x] remove the `v3.0,0` tag 
- [ ] remove 3.0.0 from https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CHANGELOG.md
- [x] remove 3.0.0 from GH releases: https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v3.0.0 
- [x] revert 3.0.0 from PyPI: https://pypi.org/project/cyclonedx-python-lib/

**Comment by jkowalleck** [comment]
@madpah  FYI

**Comment by madpah** [comment]
Thanks @jkowalleck - had not realised all this other stuff had happened too!

**Comment by madpah** [comment]
Caused by #285
