### ISSUE TITLE
FEATURE: Add full support for package URL on components

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-python-lib#31]
At the moment I can't see a way of specifying the namespace or subpath for a component purl.

https://github.com/package-url/purl-spec#purl

I hit this limitation trying to use this library for the Conan implementation and not being about to set the purl correctly.

**Comment by madpah** [comment]
Thanks @coderpatros - I think this warrants two FEATUREs:
1. This ticket to cover support for the missing coverage of the PackageURL spec
2. A new ticket to add support for automatically parsing Conan dependencies

Would you agree?
