### ISSUE TITLE
How to read in a BOM document?

### ISSUE THREAD

**Issue by rolweber** [CycloneDX/cyclonedx-python-lib#315]
Hello Team,

I need to add more info to a BOM, which I'm planning to generate with `cyclonedx-bom`. My idea was to use cyclonedx-python-lib to read in the generated BOM, then merge the additional info my team requires, then write out the enriched BOM. Looks like this idea is already failing at the "read in" step.

The [documentation says](https://cyclonedx-python-library.readthedocs.io/en/latest/modelling.html#example-bom-using-a-parser) that Parsers were moved to cyclonedx-bom. The [parsers there](https://github.com/CycloneDX/cyclonedx-python/tree/master/cyclonedx_py/parser) are for foreign formats like conda output or pip requirements files, which makes perfect sense to me. But what I need is a parser which just reads back the format(s) generated by cyclonedx-python-lib itself. That would fit better right here, for example to do round-trip tests: serialize, deserialize, check if everything's still there.

It seems this kind of parser is neither here nor there. I see an [`output`](https://github.com/CycloneDX/cyclonedx-python-lib/tree/main/cyclonedx/output) package, but no corresponding `input`. The [`parser`](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/parser/__init__.py) package has just an abstract base class. The tests [generate data](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/tests/data.py) programmatically, afaict. Did I miss something? Or is my use case that far off?

`cyclonedx-bom` supports only json and xml as [output formats](https://github.com/CycloneDX/cyclonedx-python#basic-usage), so deserializing protocol buffers doesn't seem to be an option for my idea. Besides, I haven't seen a way to deserialize protocol buffers into the objects of this lib either.

**Comment by jkowalleck** [comment]
duplicates #185

**Comment by rolweber** [comment]
Thanks. Sorry for missing the existing issue.
