### ISSUE TITLE
feat: include tests in `sdist` releases

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#336]
As of https://github.com/CycloneDX/cyclonedx-python-lib/issues/334#issuecomment-1377411800

> The _one_ thing that would be useful for downstreams is including the test files in the `sdist` uploaded to pypy: at present, these are [downloaded separately](https://github.com/conda-forge/cyclonedx-python-lib-feedstock/blob/main/recipe/meta.yaml#L11), but sometimes git tags move, github-generated source tarballs change their SHA, etc. Having a single distribution, with a published SHA256, would simplify things a bit, but it's not a huge lift, and worth it to have tests.

`sdist` releases are - as the name says - source releases, in contrast to `egg`/`wheel`/bin releases, so it should be no issue to put the tests next to the sources.

Acceptance criteria: 
- [ ] tests are part of the `sdist` bundle
- [ ] tests are not installed, when the `sdist` bundle is actually installed via `pip` or something

**Comment by jkowalleck** [comment]
@bollwyvl does the current ticket description suite your needs? 
If not, please help me shape it properly.

**Comment by bollwyvl** [comment]
Yep, that's great. Likely it's a one-liner in e.g. `pyproject.toml` or (at worst), `setup.{cfg,py}` and `MANIFEST.in`.

**Comment by jkowalleck** [comment]
okay.

next release should include the tests in the `sdist` build

**Comment by jkowalleck** [comment]
@bollwyvl 

Releases should include the tests in the `sdist` build, from now on.
I am not certain if the pure `tests` folder is enough. Please test the latest `sdist` release and tell me if it was sufficient. 

I would expect that you still need to install the test/dev dependencies somehow.
Could you check and confirm everything is as you need it?

**Comment by bollwyvl** [comment]
> if the pure `tests` folder is enough

One last missing piece of testing the package as-installed is the expectation of the relative path to the `schema` content:

```
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_spdx.py ______________________
tests/test_spdx.py:29: in <module>
    with open(path_join(dirname(__file__), '..', 'cyclonedx', 'schema', 'spdx.schema.json')) as spdx_schema:
E   FileNotFoundError: [Errno 2] No such file or directory: '$SRC_DIR/tests/../cyclonedx/schema/spdx.schema.json'
=========================== short test summary info ============================
ERROR tests/test_spdx.py - FileNotFoundError: [Errno 2] No such file or direc...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.47s ===============================
```

I've added [this patch](https://github.com/conda-forge/cyclonedx-python-lib-feedstock/pull/33/files#diff-13895a9af6f1298bd644795264808fe8dc408f327f3dd4c5ca789a392948d283) which seems to do the trick, and can do a proper PR if there isn't a whole ceremony around it with CLAs, etc.

Also note (and I _believe_ this is `poetry`-related, but have forgotten, frankly), but somehow the `LICENSE` ends up in the root of `site-packages/` when installed. We [hack around it](https://github.com/conda-forge/cyclonedx-python-lib-feedstock/pull/33/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR19), and will seldom create a problem for your users: `pip` will happily, non-deterministically clobber files all day. However, `conda` (and especially some downstream tooling like `constructor`) gets real huffy, though.

**Comment by jkowalleck** [comment]
Sounds reasonable. Will incorporate this patch in our tests.

**Comment by jkowalleck** [comment]
@bollwyvl , 

Once again, I thank you for helping improve this lib. 

The extra `LICENSE` file and the mentioned path issue should be fixed with the next bug fix release.

**Comment by jkowalleck** [comment]
ow, man. sorry.
will see how this can be fixed.
