### ISSUE TITLE
chore: use `mypy: ^1.0`

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#346]
_mypy_ does type checking of our code. for QA reasons.

in the past, we were using `mypy: >0.NNN, <1` as a dev-dependency.
_mypy_ released v1 - lets bump to the new major version.

**Comment by madpah** [comment]
Already included in `dev/4.x.x` branch.

**Comment by madpah** [comment]
Included in `4.0.0` - now released.
