### ISSUE TITLE
ExternalReference url parameters that are not XsUri cause hard to find serialization issues

### ISSUE THREAD

**Issue by schlenk** [CycloneDX/cyclonedx-python-lib#363]
The 4.0 version is nice, but has changed a few things in the serialization.

In 3.x one could use:

```python
            ExternalReference(
                type=ExternalReferenceType.WEBSITE,
                url="https://example.org",
            )
```

In 4.0, this needs some boilerplate XsUri:

```python
            ExternalReference(
                type=ExternalReferenceType.WEBSITE,
                url=XsUri("https://example.com"),
            )
```

Omitting the XsUri in 4.0 this causes a Traceback on serialization:

```python
File "c:\code\.venv\Lib\site-packages\cyclonedx\output\__init__.py", line 85, in output_to_file
    f_out.write(self.output_as_string().encode('utf-8'))
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\.venv\Lib\site-packages\cyclonedx\output\xml.py", line 70, in output_as_string
    self.generate()
  File "c:\code\.venv\Lib\site-packages\cyclonedx\output\xml.py", line 63, in generate
    self._root_bom_element = self.get_bom().as_xml(  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\.venv\Lib\site-packages\serializable\__init__.py", line 400, in _as_xml
    nested_e.append(j.as_xml(view_=view_, as_string=False, element_name=nested_key, xmlns=xmlns))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\.venv\Lib\site-packages\serializable\__init__.py", line 400, in _as_xml
    nested_e.append(j.as_xml(view_=view_, as_string=False, element_name=nested_key, xmlns=xmlns))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\.venv\Lib\site-packages\serializable\__init__.py", line 425, in _as_xml
    this_e.append(v.as_xml(view_=view_, as_string=False, element_name=new_key, xmlns=xmlns))
                  ^^^^^^^^
AttributeError: 'str' object has no attribute 'as_xml'
```

It would be nice, if the ``url`` parameters, especially for `ExternalReference` check the type of the argument. The code has Mypy type annotations listing XsUri, yes, but that does not help to figure it out at runtime.

**Comment by schlenk** [comment]
Nothing prevents that. So it is trash in -> trash out of course.

It is just some not so nice user API design that the 'url' parameter requires XsUri and not just str. I can see why this is done to make the code nicely orthogonal. 

The serialization blows up with the unhelpful Exception in that case. Some better diagnostics at serialization time would be nice, to discover the part of the model that is in an invalid state.

**Comment by jkowalleck** [comment]
> It is just some not so nice user API design that the 'url' parameter requires XsUri and not just str. 

how would a "nice user API design" look like?
What change do you suggest? Maybe you could draft a backwards-compatible change request, to show?

**Comment by schlenk** [comment]
I migrated some code, and had a few instances of this pattern setting optional URLs, e.g. in License.

```python
           License(
                ...
                url=somedict.get('URL'),
            )
```

this works nicely when url takes a str, as in Optional[str] and keeps XsUri as an implementation detail thats just a fancy validator, but needs some extra ``None`` checks when an XsUri wrapper is needed. e.g. it mutates to something ugly like:

```python
           License(
                ...
                url=XsUri(somedict['URL']) if somedict.get('URL') else None
            )
```

In addition most external users of the class probably do not care about the XsUri type for an URL. Typically they will have some form of string at hand. On reading out the URL, they will cast that away to str to feed it into other APIs. On writing they need to add boilerplace XsUri to convert the str values they have.

The only part needing that type is the serialization code and the validation step. So for most purposes visible to users of the class, the ``url`` parameter type could just be a type alias for str instead of a full blown class wrapper. The XsUri class should be an implementation detail, not a user visible part of the API.

e.g.
```python

from typing import TypeAlias
urlstr: TypeAlias str

def __init__(self, *, type: ExternalReferenceType, url: urlstr, comment: Optional[str] = None, 
              hashes: Optional[Iterable[HashType]] = None) -> None: 
     self.url = url if isinstance(url, XsUri) else XsUri(str)
     self.comment = comment 
     self.type = type 
     self.hashes = hashes or []  # type: ignore 
```

the setter/getters would obviously need to do something as well. But using the code gets nicer. If i pass in junk, it raises the proper exceptions. I can directly pass values in from other places without value wrappers and so on.

This is a little different to the Purl case, where the PackageURL class actually carries more weight.

If you see merit in improving this, i can try to do a pull request.

**Comment by jkowalleck** [comment]
see https://github.com/CycloneDX/cyclonedx-python-lib/issues/432

**Comment by jkowalleck** [comment]
closed.

downstream users may write themselves a wrapper, doing the exact same an in-bound code would do:
test if a URI is string, and if som convert it to `XsUri`.



applies like (based on given examples above)
```py
makeXsUriFromAny(v) -> XsUri | None:
  return XsUri(v) if isinstance(v, str) else None

License(
    ...
    url=makeXsUriFromAny(somedict['URL'])
)
```
