### ISSUE TITLE
Authors creation issue

### ISSUE THREAD

**Issue by jblu42** [CycloneDX/cyclonedx-python-lib#409]
I am creating an SBOM with (simplified, not all code included):

mybom = Document()
mybom.version = Version(2, 3)
mybom.metadata.authors.add(contact)

which creates something like:

 "metadata": {"authors": ["A M"], "timestamp": "2023-06-14T14:11:33.372355+00:00", "tools": [{"name": "python-bom", "vendor": "XY", "version": "5.0.1"}, {"externalReferences": [{"type": "build-system", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/actions"}, {"type": "distribution", "url": "https://pypi.org/project/cyclonedx-python-lib/"}, {"type": "documentation", "url": "https://cyclonedx.github.io/cyclonedx-python-lib/"}, {"type": "issue-tracker", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/issues"}, {"type": "license", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/LICENSE"}, {"type": "release-notes", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CHANGELOG.md"}, {"type": "vcs", "url": "https://github.com/CycloneDX/cyclonedx-python-lib"}, {"type": "website", "url": "https://cyclonedx.org"}], "name": "cyclonedx-python-lib", "vendor": "CycloneDX", "version": "4.0.0"}, {"name": "ABC", "vendor": "DEF", "version": "2022.1.1#17708"}]}, "serialNumber": "urn:uuid:fe093ce2-3539-4b14-8bde-7a9f692fd75f", "version": 1, "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json", "bomFormat": "CycloneDX", "specVersion": "1.4"}

I try to import my SBOM into dependency track, but it throws an error. The comment from dependency track was:

This is expected behavior as the BOM is invalid. metadata.authors [is an array of objects](https://cyclonedx.org/docs/1.4/json/#metadata_authors), not an array of strings.

Am I using the wrong code here to create the author or is it an error in the library?

**Comment by jkowalleck** [comment]
> Am I using the wrong code here to create the author or is it an error in the library?

could you provide the python code you used to create the JSON?

**Comment by jblu42** [comment]
Here is a stripped down version of my code, reproducing this error:
[sample_python.txt](https://github.com/CycloneDX/cyclonedx-python-lib/files/12237400/sample_python.txt)
[output.txt](https://github.com/CycloneDX/cyclonedx-python-lib/files/12237401/output.txt)

**Comment by jblu42** [comment]
This is the error from Dependency Track:
2023-08-02 07:35:25,330 ERROR [BomUploadProcessingTask] Error while processing bom
org.cyclonedx.exception.ParseException: Unable to parse BOM from byte array
        at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:70)
        at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:105)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.cyclonedx.model.OrganizationalContact` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('My Name')

**Comment by jkowalleck** [comment]
re https://github.com/CycloneDX/cyclonedx-python-lib/files/12237400/sample_python.txt
```py
contact = "My Name"

mybom = Bom()
mybom.metadata.tools.add(Tool(
        vendor='Myself',
        name='python-bom',
        version='1.0'
    )) 
mybom.metadata.authors.add(contact)
```

`mybom.metadata.authors` shoudl be a set of `OrganizationalContact`.
see https://cyclonedx-python-library.readthedocs.io/en/latest/autoapi/cyclonedx/model/bom/index.html#cyclonedx.model.bom.BomMetaData.authors

You are adding a `str` instead of an instance of `OrganizationalContact`
You need to fix your code.
