### ISSUE TITLE
Add version string to package, following PEP 396

### ISSUE THREAD

**Issue by hedtke** [CycloneDX/cyclonedx-python-lib#416]
In a project where I need to support python 3.6, I want to differentiate between major version 3 and 4 of this package. See https://github.com/conan-io/conan-extensions/pull/66/commits/96fb5a7c0a5a56b736e7582ef98511a96b917ddb

To help use-cases like mine, please consider adding `cyclonedx.__version__` following PEP 396, see https://peps.python.org/pep-0396/

**Comment by jkowalleck** [comment]
PHP0396 was rejected. so it is not a standard.
 i will check for well-known alternatives.

**Comment by jkowalleck** [comment]
some background and concerns: 
there is no standard for a `__version__` or anything else, and the draft of PEP396 asks for a string.

a string is not comparable in terms of versioning.
a tuple would be best since it is fully comparable, like `(1,33,7) <= (1, 42)`.

as long as there is no proper standard, i'd better not introduce such changes, but i will have them prepared anyway. ;-)

**Comment by hedtke** [comment]
Only because something is not standard, does not forbid it. If there is a new standard in the future, this could be supported as well. Many packages have such a feature. What about finding a way (any way: `__version__` string, or method `version() -> tuple` in init, or ...) and later supporting the then approved standard as well.

**Comment by jkowalleck** [comment]
> Only because something is not standard, does not forbid it. If there is a new standard in the future, this could be supported as well. Many packages have such a feature. What about finding a way (any way: `__version__` string, or method `version() -> tuple` in init, or ...) and later supporting the then approved standard as well.

i have no problems with fixing the issue.
So far, I just made clear why I might consider a solution that is not the one that was proposed.

**Comment by hedtke** [comment]
I am happy with any way to get the version :-)

BTW: As cyclonedx adds itself into the tools section of the SBOM, it already knows which version it is. How does one access that?

**Comment by hedtke** [comment]
Backporting the chosen way into v3 would be ideal for my use-case. Where I have to differentiate between v3 and v4. But that is just a nice-to-have

**Comment by jkowalleck** [comment]
solution will probably be a string, that follows https://peps.python.org/pep-0440/
will probably use `__versoin__` in some way.

**Comment by jkowalleck** [comment]
>  As cyclonedx adds itself into the tools section of the SBOM, it already knows which version it is. How does one access that

untested code, maybe something like 
```py
my_tool = next(t for t in bom.metadata.tools if t.name=='my_tool', None)
```
should cause variable `my_tool` to be either `None` or some `Tool` that matches the predicate `.name=='my_tool'`
