### ISSUE TITLE
[BUILD] 4.2.2 puts extra files in root of site-packages

### ISSUE THREAD

**Issue by bollwyvl** [CycloneDX/cyclonedx-python-lib#435]
A look at the files in the [4.2.2 wheel](https://files.pythonhosted.org/packages/a7/12/e9aa5af14a8158cac722fe2c098d8cc6dd3b6574a08703de35849286f04a/cyclonedx_python_lib-4.2.2-py3-none-any.whl) shows the return of the condition from [#336](https://github.com/CycloneDX/cyclonedx-python-lib/issues/336#issuecomment-1380705537).

On [conda-forge](https://github.com/conda-forge/cyclonedx-python-lib-feedstock/pull/40), we'll probably just delete them. They are unlikely to truly offend anything (other than other packages that have similar quirks), but just good manners.

**Comment by jkowalleck** [comment]
ow, man. sorry.
will see how this can be fixed.

**Comment by jkowalleck** [comment]
thing is that this file MUST to be shipped, along with the `NOTICE` file, for legal reasons.
the files MUST to be shipped, but dont need to be installed.

sorry.

**Comment by jkowalleck** [comment]
@bollwyvl I feel bad for the inconvenience,
but i cannot provide a quick fix, unless https://github.com/python-poetry/poetry/issues/8441 got implemented.

**Comment by bollwyvl** [comment]
Right, they certainly need to be shipped, but build backends generally seem to have a way to do this where they end up in the `.dist-info` folder of a wheel. Again, probably not hurting anybody.

**Comment by jkowalleck** [comment]
build backend has not proper functionality for it, yet. 
a fix depends on https://github.com/python-poetry/poetry/issues/8441
