### ISSUE TITLE
Downstream type hints?

### ISSUE THREAD

**Issue by woodruffw** [CycloneDX/cyclonedx-python-lib#52]
First of all, thanks for this fantastic library!

I'm currently working on using `cyclonedx-python-lib` to generate SBOMs within [`pip-audit`](https://github.com/trailofbits/pip-audit).

Our codebase is fully typechecked (via MyPy), and it looks like this library is too! But we can't currently consume your type hints, since the `cyclonedx` package doesn't include a `py.typed` file per [PEP 561](https://www.python.org/dev/peps/pep-0561/). 

Is there any objection to including that file, so that downstream users can typecheck their API use? If not, I can go ahead and create a PR -- it should be just a 2 or 3 line change.

**Comment by jkowalleck** [comment]
thanks you very much for the hint, @woodruffw :+1: 
we are currently working on this issue.

**Comment by woodruffw** [comment]
Awesome, thanks a ton! Let me know if I can help with testing or anything else.

**Comment by jkowalleck** [comment]
@woodruffw the release [v0.11.0](https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v0.11.0) included PEP 561 compatibility.

Could you see if it suites your needs?

**Comment by woodruffw** [comment]
Looks like the type hints are working! Thanks a ton for adding them so quickly. The only outstanding issues preventing me from using them are in #61.

**Comment by madpah** [comment]
Great news @woodruffw - #61 is merged now and building - point release expected shortly.
