### ISSUE TITLE
Components with no `bom_ref` specified break dependency tree

### ISSUE THREAD

**Issue by jkugler** [CycloneDX/cyclonedx-python-lib#539]
As of version 6.0, the library no longer creates a `uuid4` string for the bom_ref when none is provided. However, for linking dependencies, it relies on the the `.value` of the bom_ref object, and thus this breaks dependency linking.

Talking with @jkowalleck on Slack, he thought changing `==` to `is` would fix the problem here: https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/model/bom.py#L555

Example script to demonstrate the problem (based off of https://cyclonedx-python-library.readthedocs.io/en/latest/examples.html)

```python
#!/usr/bin/env python3

from cyclonedx.model.bom import Bom
from cyclonedx.model.component import Component, ComponentType
from cyclonedx.output.json import JsonV1Dot5

bom = Bom()
bom.metadata.component = root_component = Component(
    name='myApp',
    type=ComponentType.APPLICATION,
)

component1 = Component(
    type=ComponentType.LIBRARY,
    name='some-component',
)
bom.components.add(component1)
bom.register_dependency(root_component, [component1])

component2 = Component(
    type=ComponentType.LIBRARY,
    name='some-library',
)
bom.components.add(component2)
bom.register_dependency(component1, [component2])

component3 = Component(
    type=ComponentType.LIBRARY,
    name='another-library',
)
bom.components.add(component3)
bom.register_dependency(root_component, [component3])

print(JsonV1Dot5(bom).output_as_string(indent=2))
```
When run, that produces this section:
```json
  "dependencies": [
    {
      "dependsOn": [
        "BomRef.8312066161950966.2909051244858393"
      ],
      "ref": "BomRef.7208056703935715.03775139686960205"
    }
  ],
```
which shows the root component depending on `some-component` (`component1` in the code) and no other dependency relationships.

**Comment by jkowalleck** [comment]
will add test cases to older versions, for regression and showcasing-purposes,
and then forward-port those and add fixes.

I am planning to have all affected major versions fixed.

**Comment by jkowalleck** [comment]
fix was released via https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v6.4.1
