### ISSUE TITLE
class `Diff` is not serializable

### ISSUE THREAD

**Issue by rcross-lc** [CycloneDX/cyclonedx-python-lib#556]
[Gist with example code reproducing the issue.](https://gist.github.com/rcross-lc/9ea2336a810281307cb1e638b8ac398e)

Expected output:

```
...
"patches": [
  {
    "diff": {
      "url": "https://en.wikipedia.org/wiki/Diff"
    },
    "type": "backport"
  }
]
...
```

Actual output: 
```
...
"patches": [
  {
    "diff": "<Diff url=https://en.wikipedia.org/wiki/Diff>",
    "type": "backport"
  }
]
...
```

The example also fails to deserialize the json as well.

**Comment by jkowalleck** [comment]
fix applied via https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v6.4.3
