### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#60]
Python 3.10 officially released on 09-Nov-2021 - support for this should be included / verified.

**Comment by jkowalleck** [comment]
acc crit: 
- [ ] have CI/CT running in py3.10 - and pass
- [ ] have tox tunning in py3.10 = and pass
- [ ] added the py3.10 trove / classifiers "Programming Language :: Python :: 3.10"
