### ISSUE TITLE
[BUG] OrganizationalEntity validation error should not be raised

### ISSUE THREAD

**Issue by pombredanne** [CycloneDX/cyclonedx-python-lib#600]
A spec-valid JSON BOM 1.4 with `{"supplier":{"name":""},` fails to load and should not fail.

The code at https://github.com/CycloneDX/cyclonedx-python-lib/blob/42931016e9060ddc6a1c15d99c10379821bfba85/cyclonedx/model/contact.py#L282 makes loading a BOM that has a name as an empty string to fail.

There is nothing in the spec that says this is invalid... I can accept that there is a way to do a strict validation, but this should be an option AND this should not make it impossible to load a JSON. If this cannot be loaded, fixing the issue is made much harder.

The spec at https://github.com/CycloneDX/specification/blob/1.6/schema/bom-1.4.schema.json#L203 does not have any such requirements, same in https://cyclonedx.org/docs/1.4/xml/#type_organizationalEntity and other versions of the spec.

IMHO such as exception here and elsewhere SHOULD NEVER be raised unless an explicit request for a strict validation for empty values is requested above and beyond what is in the spec. 

@tdruez ping

**Comment by pombredanne** [comment]
@jkowalleck FYI, this is the kind of workaround that is needing short term to read CDX from  some weird tool that produce these documents:

https://github.com/nexB/scancode.io/commit/1bd0e4de4daeee53c8de99d2a8eda050dfa58d12#diff-ea7df675af2b46146067bf4d4314ece949da068c9ae5635fa423c19f008209b3R211

**Comment by jkowalleck** [comment]
expected to be fixed in https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v7.3.4

**Comment by pombredanne** [comment]
Thank you.
