### ISSUE TITLE
Changelog for 7.3.3 basically unreadable

### ISSUE THREAD

**Issue by 0-wiz-0** [CycloneDX/cyclonedx-python-lib#616]
There's lots of HTML code mixed in and I can't make heads or tails of it. Can you please improve its formatting? Thank you.

----

https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v7.3.3

**Comment by jkowalleck** [comment]
acknowledged.

changelog is autogenerated by https://python-semantic-release.readthedocs.io/en/latest/
in the version 9.x they messed up the changelog templates ... we always were hoping they would fix it....

if they dont, feel free to reach out to them having the templates improved,
or pullrequest a better template to this very repository. instructions are here: https://python-semantic-release.readthedocs.io/en/latest/changelog_templates.html

**Comment by jkowalleck** [comment]
currently using: `python-semantic-release/python-semantic-release@v9.1.1`
https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/.github/workflows/release.yml#L111

**Comment by jkowalleck** [comment]
my personal favorite would be: dont render the full commit messages, but only the commit title ... 

if this was applied to the changelog, i could manually carry it over to the already made release notes. ...

**Comment by jkowalleck** [comment]
regenerated change logs via #627

updated https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v7.3.3

**Comment by gsemet** [comment]
You can use committizen it works very well.

https://pypi.org/project/commitizen/
