### ISSUE TITLE
Empty Component Property cannot be deserialized

### ISSUE THREAD

**Issue by schlenk** [CycloneDX/cyclonedx-python-lib#630]
A component with an empty property cannot be deserialized from XML.
At least cyclonedx-cli validate considers it as a valid.

This component cannot be deserialized:

```xml    
<ns0:component type="library" bom-ref="example@15.8.0">
      <ns0:name>example</ns0:name>
      <ns0:version>15.8.0</ns0:version>
      <ns0:properties>
        <ns0:property name="cdx:npm:package:path" />
      </ns0:properties>
</ns0:component>
```

It fails with a traceback, as no value is found for the property:

```
  File ".venv\Lib\site-packages\serializable\__init__.py", line 603, in from_xml
    _data[decoded_k].append(prop_info.concrete_type.from_xml(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\serializable\__init__.py", line 603, in from_xml
    _data[decoded_k].append(prop_info.concrete_type.from_xml(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\serializable\__init__.py", line 656, in from_xml
    return cls(**_data)
           ^^^^^^^^^^^^
TypeError: Property.__init__() missing 1 required keyword-only argument: 'value'
```

Script and data to reproduce:
[property_parse.zip](https://github.com/user-attachments/files/15764178/property_parse.zip)

Versions used:

* Python 3.11
* cyclonedx-python-lib 7.4.0
* py-serializable      1.0.3

**Comment by jkowalleck** [comment]
thank you for the report and the reproducible example.
are you willing to provide/work on a fix?

**Comment by jkowalleck** [comment]
solution: make the `value` of the property object optional, default `None`

**Comment by jkowalleck** [comment]
@schlenk ,
thank you for the report and the reproducible example.
are you willing to provide/work on a fix?

**Comment by schlenk** [comment]
I added a pull request for the code change, but have no idea how to properly add a test for it, as the test data setup is a bit confusing.
