### ISSUE TITLE
[BUG] `HashType.from_composite_str` fails to recognize `BLAKE2b` 

### ISSUE THREAD

**Issue by gmscofield** [CycloneDX/cyclonedx-python-lib#652]
In this file https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/model/__init__.py, line 440 cannot make the correct key in HashAlgorithm.
https://github.com/CycloneDX/cyclonedx-python-lib/blob/d7e517b160982fe9f4ea19d489f855db459d81fc/cyclonedx/model/__init__.py#L441-L444

**Comment by jkowalleck** [comment]
@gmscofield,
Could you add some context? 
how did you call `HashType.from_composite_str`? What were the parameters? How did this all come together?

**Comment by gmscofield** [comment]
> @gmscofield, Could you add some context? how did you call `HashType.from_composite_str`? What were the parameters? How did this all come together?

Sorry, I will add some detailed context.
I call `HashType.from_composite_str` by `HashType.from_composite_str("BLAKE2b-256:123456789")`. BLAKE2b-256 algorithm is in the class HashAlgorithm. But the function `HashType.from_composite_str` will get the wrong algorithm `BLAKE2b_b-256`.

**Comment by schlenk** [comment]
This looks like an underspecified `HashType.from_composite_str` method, it should probably document the recognized prefixes.

The Blake2 RFC (https://datatracker.ietf.org/doc/html/rfc7693) mentions two forms of Blake2: Blake2b for 64-bit and Blake2s for 32-bit systems.

The current code assumes 'blake2' as a prefix always means 'BLAKE2b' and considers everything after the first 6 chars as suffix, so a 'b' ends up in the suffix part, if someone correctly specifies a prefix like 'BLAKE2b-256'.
 
So a fix could recognize both 'blake2' and 'blake2b' as valid prefixes and use them accordingly (as CycloneDX does not specify Blake2s support...).

**Comment by jkowalleck** [comment]
thank you for clarification.

would you be open for contributing a fix and recreation-tests?

**Comment by jkowalleck** [comment]
thank you for the fix, @schlenk
