### ISSUE TITLE
Importing cyclonedx-python-lib modules disables Python logging

### ISSUE THREAD

**Issue by njv299** [CycloneDX/cyclonedx-python-lib#679]
I stop seeing log messages on the console when I import certain modules from this library. 

To replicate:

Running this works fine and prints the expected log message:
```
% python
Python 3.10.6 (main, Mar 29 2024, 09:11:02) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG, format="[%(levelname)-8s|%(module)-10.10s] %(message)s")
>>> logger = logging.getLogger(__name__)
>>> logger.debug("Hello world!")
[DEBUG   |<stdin>   ] Hello world!
>>>
```

But if I import any significant portion of the CycloneDX library, my log messages are suppressed:
```
% python
Python 3.10.6 (main, Mar 29 2024, 09:11:02) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import cyclonedx.model
>>> logging.basicConfig(level=logging.DEBUG, format="[%(levelname)-8s|%(module)-10.10s] %(message)s")
>>> logger = logging.getLogger(__name__)
>>> logger.debug("Hello world!")
>>> 
```

I've looked through the code fairly extensively and haven't found where the suppression is happening (there's no interaction with the `logging` module in the entire codebase from what I can tell), so I think it's happening as a side-effect of importing one of the dependent libraries.

Does anyone have any suggestions of how to avoid this behavior?

**Comment by jkowalleck** [comment]
this seams unintended.

a quick search showed no related code to `logging` in this lib: <https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-python-lib+logging+language%3APython&type=code&l=Python>

tested for reproducibility:
```text
Python 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import cyclonedx.model
>>> logging.basicConfig(level=logging.DEBUG, format="[%(levelname)-8s|%(module)-10.10s] %(message)s")
>>> logger = logging.getLogger(__name__)
>>> logger.debug("Hello world!")
[DEBUG   |<stdin>   ] Hello world!
>>> print(cyclonedx.__version__)
7.6.1
```

could not reproduce. which version of the lib did yoou use?

**Comment by jkowalleck** [comment]
this seams unintended.

a quick search showed no related code to `logging` in this lib: <https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-python-lib+logging+language%3APython&type=code&l=Python>

tested for reproducibility:
```text
Python 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import cyclonedx.model
>>> logging.basicConfig(level=logging.DEBUG, format="[%(levelname)-8s|%(module)-10.10s] %(message)s")
>>> logger = logging.getLogger(__name__)
>>> logger.debug("Hello world!")
[DEBUG   |<stdin>   ] Hello world!
>>> print(cyclonedx.__version__)
7.6.1
```

could not reproduce. 


@njv299 , which version of the lib did you use? 

PS: I remember there was an old version of this lib that modified the logger. this is no longer the case in the current versions.

**Comment by DjDeepDive** [comment]
Verified behavior on `cyclonedx-python-lib` version < 6, i.e. 5.2.0.  6.4.4 and above seems to have resolved this issue.
