### ISSUE TITLE
feat: add `bom.definitions`

### ISSUE THREAD

**Issue by hakandilek** [CycloneDX/cyclonedx-python-lib#697]
This might also be considered as a part of #696 since the [`bom.definitions`](https://cyclonedx.org/docs/1.6/json/#definitions) is introduced in v1.6.

We're currently using `bom.definitions` to indicate that the given SBOM aligns with certain standards. It'd be nice to have it supported in the library.

**Comment by jkowalleck** [comment]
@hakandilek ,

You know your use cases best, and you could provide examples and tests.
Would you be interested in contributing this feature?
