### ISSUE TITLE
[FEATURE]: Add support for dependencies (`bom.dependencies`)

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#7]
Raising here from https://github.com/CycloneDX/cyclonedx-python/issues/40 given the split into this library.

CycloneDX schema version 1.2+ supports `bom.dependencies` which can be used to generate dependency tree graphs from CycloneDX BOMs.

This library currently has no support for `bom.dependencies`.

**Comment by jkowalleck** [comment]
i wrote some hints/thoughts, when i did the implementation for this feature for the PHP library.
:information_source: this might come in handy: https://github.com/CycloneDX/cyclonedx-php-library/blob/master/docs/dev/decisions/BomDependencyDataModel.md
