### ISSUE TITLE
pre-commit hook fails with provided environments not found 

### ISSUE THREAD

**Issue by weichslgartner** [CycloneDX/cyclonedx-python-lib#721]
The pre-commit hook fails for me as follows:

```bash
mypy.....................................................................Failed
- hook id: system
- exit code: 254

ROOT: HandledError| provided environments not found in configuration file:
mypy-locked
```
in the `.pre-commit-config.yaml` has the entry:
```
entry: poetry run tox -e mypy-locked
```

the `tox.ini` looks like:

```
[tox]
minversion = 4.0
envlist =
    flake8
    mypy-{current,lowest}
    py{313,312,311,310,39,38}-{allExtras,noExtras}
    bandit
```

If i change it to `mypy-{current,lowest,locked}` it works for me. Am i missing something? Where does the mypy-locked env come from?

**Comment by jkowalleck** [comment]
Thank you bringing this to my attention, @weichslgartner 👍 .

The `mypy-locked` existed a long  while ago. It was dropped in favor of the `-current`/`-lowest` solution.
I personally do not use these hooks, so I probably forgot to migrate them.

If you are a user of this feature, please pullrequest a fix. I guess `mypy-current` should be enough in the hook.
