### ISSUE TITLE
feat: add helper method to generate`BomLink`

### ISSUE THREAD

**Issue by saquibsaifee** [CycloneDX/cyclonedx-python-lib#726]
Improve the process of creating and validating BOM-Link URIs within XsUri.
This enhancement would standardize BOM-Link creation within XsUri, reduce potential errors in URI formation, and simplify BOM-Link validation.

from @jkowalleck 
> A possible solution could be something like a classmethod 
`XsUri.make_BomLink(cls, serialnumber: Union[UUID, string], version: int = 1, bom_ref: Optional[Union[string, BomRef]] = None) -> XsUri`
> 
> And we would, of course, add a method `XsUri.is_BomLink(self) -> bool`

**Comment by jkowalleck** [comment]
@saquibsaifee , is this feature something you would contribute?

**Comment by saquibsaifee** [comment]
Yes, I am giving it a try as we speak

**Comment by jkowalleck** [comment]
we already have parts ofg the bom-link patetrn here: https://github.com/CycloneDX/cyclonedx-python-lib/blob/70cf9b4a17abdbfc4874c3ddbefa751eb32547c4/cyclonedx/model/bom.py#L646-L647 
maybe you could refactor that?  or maybe not, ... whatever suites you.

**Comment by saquibsaifee** [comment]
Not able to link the PR, so mentioning here. #728 

I'll continue the work
