### ISSUE TITLE
store build artifacts on release

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#87]
as a <> i want build artifacts added to a release, so PyPI is not my single point of source.

use https://github.com/actions/upload-release-asset
to add the wheel(`build/*.whl`) and source (`build/*.tar.gz`) artifacts to the release

----

how to do it: see an example here: https://github.com/k4cg/nichtparasoup/blob/3.0-dev/.github/workflows/release.yaml

----

build artifacts to store
* dist release
* source release

**Comment by madpah** [comment]
@jkowalleck - aren't these already added to GitHub Releases: https://github.com/CycloneDX/cyclonedx-python-lib/releases?

**Comment by jkowalleck** [comment]
dont see dist or source releases.
what is added today is: 
* docker image SBOM - by github-workflow
* snapshot of the repository - done by github 


what we lack today is: 
* the dist artifacts that are uploaded to PyPI (and can finally be found here: https://pypi.org/project/cyclonedx-python-lib/#files)
  * source dist file 
  * wheel dist file

**Comment by madpah** [comment]
Not sure I agree - in our deploy workflow, we publish to GitHub Releases:
![Screenshot 2021-12-22 at 12 14 13](https://user-images.githubusercontent.com/10280392/147091283-4ec994b7-13a9-4751-8278-540352e8c930.png)

??

**Comment by jkowalleck** [comment]
you are totally right, @madpah 
work is done already, ticket was invalid. will close it.
